# Generated by Django 4.2.6 on 2024-03-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_post_created_by_alter_post_public_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='public_date',
            new_name='created_on',
        ),
        migrations.AddField(
            model_name='post',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
